### ISSUE TITLE
AdditionalPropertiesDeserializer throws exception when json with null value attribute is encountered

### ISSUE THREAD

**Issue by dabasvijay** [CJSCommonPlatform/utilities#19]
AdditionalPropertiesDeserializer  throws exception when json with null value attribute is encountered.

**Comment by allanmckenzie** [comment]
Fixed: version 1.13.0-SNAPSHOT

Though you will need to wait for the next release of the framework to be able to use it

**Comment by purple52** [comment]
We should release change this as 1.12.1 and release 3.1.3 of the framework. Then we can close this.
